const fs = require('fs');
const path = require('path');

const baseDir = path.join(__dirname, 'src', 'app', 'api', 'mobile');
const collection = {
  info: {
    name: "BDS All Mobile APIs",
    description: "Autogenerated collection for all mobile endpoints.",
    schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  variable: [
    { key: "base_url", value: "http://localhost:3000", type: "string" },
    { key: "jwt_token", value: "YOUR_MOBILE_JWT_TOKEN", type: "string" }
  ],
  item: []
};

function getFiles(dir, parentFolderArray) {
  const items = fs.readdirSync(dir, { withFileTypes: true });
  let folderHasRoutes = false;
  
  for (const item of items) {
    const fullPath = path.join(dir, item.name);
    
    if (item.isDirectory()) {
      const folderObj = {
        name: item.name.replace('[', ':').replace(']', ''),
        item: []
      };
      const childHasRoutes = getFiles(fullPath, folderObj.item);
      if (childHasRoutes) {
        parentFolderArray.push(folderObj);
        folderHasRoutes = true;
      }
    } else if (item.isFile() && item.name === 'route.js') {
      const relativePath = path.relative(baseDir, dir).replace(/\\/g, '/');
      const routeParts = relativePath.split('/').filter(Boolean);
      
      const endpointName = routeParts.length > 0 ? routeParts[routeParts.length - 1].replace('[', ':').replace(']', '') : 'root';
      
      let method = "GET";
      const pathStr = relativePath.toLowerCase();
      if (pathStr.includes('register') || pathStr.includes('login') || pathStr.includes('create-invoice') || pathStr.includes('execute-payment') || pathStr.includes('confirm') || pathStr.includes('send') || pathStr.includes('verify') || pathStr.includes('reset') || pathStr.includes('update') || pathStr.includes('upload')) {
        method = "POST";
      }

      const requestObj = {
        name: endpointName,
        request: {
          method: method,
          header: [
             { key: "Authorization", value: "Bearer {{jwt_token}}" },
             { key: "Content-Type", "value": "application/json" }
          ],
          url: {
            raw: "{{base_url}}/api/mobile/" + relativePath.replace(/\[([^\]]+)\]/g, ':'),
            host: ["{{base_url}}"],
            path: ["api", "mobile", ...routeParts.map(p => p.replace(/\[([^\]]+)\]/g, ':'))]
          }
        }
      };
      
      // Auto-fill body for known requests
      if (method === 'POST') {
         requestObj.request.body = { mode: 'raw', raw: "{}" };
      }
      
      parentFolderArray.push(requestObj);
      folderHasRoutes = true;
    }
  }
  return folderHasRoutes;
}

getFiles(baseDir, collection.item);

fs.writeFileSync(path.join(__dirname, 'BDS_All_Mobile_APIs.postman_collection.json'), JSON.stringify(collection, null, 2));
console.log('Generated BDS_All_Mobile_APIs.postman_collection.json');
